// Use extractbookmarks.py to convert Wikipedia bookmarks to array bookmarks
// Export browser bookmarks as bookmarks.html
// Run in Terminal (see /assets/misc-code): python extractbookmarks.py
// *Verify that the bookmarks extracted in bookmarks.js are the ones desired to be included here as the python script will export ALL Wikipedia bookmarks, including those outside of a dedicated Wikipedia folder (in this case will need to delete the last portion of extracted bookmarks that fall outside of the Wikipedia folder)
const bookmarks = [
    "https://en.wikipedia.org/wiki/Unexpected_hanging_paradox",
    "https://en.wikipedia.org/wiki/Debate_on_traditional_and_simplified_Chinese_characters",
    "https://en.wikipedia.org/wiki/Fiat_justitia_ruat_caelum",
    "https://en.wikipedia.org/wiki/Tesseract",
    "https://en.wikipedia.org/wiki/Saccade",
    "https://en.wikipedia.org/wiki/Thousand_Character_Classic",
    "https://en.wikipedia.org/wiki/Simpson%27s_paradox",
    "https://en.wikipedia.org/wiki/Radical_(Chinese_characters)",
    "https://en.wikipedia.org/wiki/Lion-Eating_Poet_in_the_Stone_Den",
    "https://en.wikipedia.org/wiki/Razor_(philosophy)",
    "https://en.wikipedia.org/wiki/23_enigma",
    "https://en.wikipedia.org/wiki/Coram_Deo",
    "https://en.wikipedia.org/wiki/William_Safire",
    "https://en.wikipedia.org/wiki/Hanshan_Temple",
    "https://en.wikipedia.org/wiki/Pidgin",
    "https://en.wikipedia.org/wiki/Cross-Strait_relations",
    "https://en.wikipedia.org/wiki/Occam%27s_razor",
    "https://en.wikipedia.org/wiki/Mathematical_beauty",
    "https://en.wikipedia.org/wiki/Anatomical_terms_of_location",
    "https://en.wikipedia.org/wiki/Retinoscopy",
    "https://en.wikipedia.org/wiki/Texas_sharpshooter_fallacy",
    "https://en.wikipedia.org/wiki/Birthday_problem",
    "https://en.wikipedia.org/wiki/Belphegor%27s_prime",
    "https://en.wikipedia.org/wiki/Kerning",
    "https://en.wikipedia.org/wiki/ROT13",
    "https://en.wikipedia.org/wiki/Tremor",
    "https://en.wikipedia.org/wiki/Primum_non_nocere",
    "https://en.wikipedia.org/wiki/Canine_cancer_detection",
    "https://en.wikipedia.org/wiki/List_of_United_States_Presidents_by_net_worth",
    "https://en.wikipedia.org/wiki/Rod_of_Asclepius",
    "https://en.wikipedia.org/wiki/Backcrossing",
    "https://en.wikipedia.org/wiki/Curling",
    "https://en.wikipedia.org/wiki/List_of_legally_mononymous_people",
    "https://en.wikipedia.org/wiki/Imhotep",
    "https://en.wikipedia.org/wiki/Fait_Accompli",
    "https://en.wikipedia.org/wiki/Ave_Maria_(Bach/Gounod)",
    "https://en.wikipedia.org/wiki/1916_Cumberland_vs._Georgia_Tech_football_game",
    "https://en.wikipedia.org/wiki/Temple_Grandin",
    "https://en.wikipedia.org/wiki/Samarkand",
    "https://en.wikipedia.org/wiki/Causal_loop",
    "https://en.wikipedia.org/wiki/Neil_Gorsuch",
    "https://en.wikipedia.org/wiki/Glossary_of_gene_expression_terms",
    "https://en.wikipedia.org/wiki/Begich_Towers",
    "https://en.wikipedia.org/wiki/Doubling_time",
    "https://en.wikipedia.org/wiki/Ship_of_Theseus",
    "https://en.wikipedia.org/wiki/God_Shammgod",
    "https://en.wikipedia.org/wiki/Rifleman's_Creed",
    "https://en.wikipedia.org/wiki/Ohio_City,_Ohio",
    "https://en.wikipedia.org/wiki/The_Death_of_the_Author",
    "https://en.wikipedia.org/wiki/Rule_of_72",
    "https://en.wikipedia.org/wiki/WHO_Model_List_of_Essential_Medicines",
    "https://en.wikipedia.org/wiki/Kenosis",
    "https://en.wikipedia.org/wiki/Champernowne_constant",
    "https://en.wikipedia.org/wiki/Robert_Burns_Woodward",
    "https://en.wikipedia.org/wiki/Dynamic_and_formal_equivalence",
    "https://en.wikipedia.org/wiki/Survivorship_bias",
    "https://en.wikipedia.org/wiki/Median_lethal_dose",
    "https://en.wikipedia.org/wiki/Tu_quoque",
    "https://en.wikipedia.org/wiki/Binaural_beats",
    "https://en.wikipedia.org/wiki/Nicholas_Barbon",
    "https://en.wikipedia.org/wiki/Wikipedia:Deleted_articles_with_freaky_titles",
    "https://en.wikipedia.org/wiki/Nightingale_floor",
    "https://en.wikipedia.org/wiki/Petrichor",
    "https://en.wikipedia.org/wiki/Buffalo_buffalo_Buffalo_buffalo_buffalo_buffalo_Buffalo_buffalo",
    "https://en.wikipedia.org/wiki/Social_enterprise",
    "https://en.wikipedia.org/wiki/Parasocial_interaction",
    "https://en.wikipedia.org/wiki/Buridan%27s_ass",
    "https://en.wikipedia.org/wiki/H-index",
    "https://en.wikipedia.org/wiki/Best_of_all_possible_worlds",
    "https://en.wikipedia.org/wiki/Anthropic_principle",
    "https://en.wikipedia.org/wiki/Robert_C._Baker",
    "https://en.wikipedia.org/wiki/Anselm_of_Canterbury",
    "https://en.wikipedia.org/wiki/Clubbed_thumb",
    "https://en.wikipedia.org/wiki/List_of_Metropolitan_Statistical_Areas",
    "https://en.wikipedia.org/wiki/Leidenfrost_effect",
    "https://en.wikipedia.org/wiki/Birthday-number_effect",
    "https://en.wikipedia.org/wiki/Toxin-antitoxin_system",
    "https://en.wikipedia.org/wiki/Filter_bubble",
    "https://en.wikipedia.org/wiki/Electrical_disruptions_caused_by_squirrels",
    "https://en.wikipedia.org/wiki/Color_of_water",
    "https://en.wikipedia.org/wiki/Stochastic_process",
    "https://en.wikipedia.org/wiki/Dunning%E2%80%93Kruger_effect",
    "https://en.wikipedia.org/wiki/Sett",
    "https://en.wikipedia.org/wiki/Vinculum_(symbol)",
    "https://en.wikipedia.org/wiki/Pareto_principle",
    "https://en.wikipedia.org/wiki/List_of_mammals_of_Israel",
    "https://en.wikipedia.org/wiki/Between_Scylla_and_Charybdis",
    "https://en.wikipedia.org/wiki/Aegis",
    "https://en.wikipedia.org/wiki/Arrow_of_time",
    "https://en.wikipedia.org/wiki/Non-apology_apology",
    "https://en.wikipedia.org/wiki/Decimal_time",
    "https://en.wikipedia.org/wiki/Quill_and_Dagger#At_Cornell",
    "https://en.wikipedia.org/wiki/Uyghurs",
    "https://en.wikipedia.org/wiki/Santa_language",
    "https://en.wikipedia.org/wiki/Monte_Carlo_method",
    "https://en.wikipedia.org/wiki/House_of_Kamehameha",
    "https://en.wikipedia.org/wiki/Lucasian_Professor_of_Mathematics",
    "https://en.wikipedia.org/wiki/Names_of_God_in_Judaism",
    "https://en.wikipedia.org/wiki/Lectio_Divina",
    "https://en.wikipedia.org/wiki/Modus_operandi",
    "https://en.wikipedia.org/wiki/Big_Four_accounting_firms",
    "https://en.wikipedia.org/wiki/Pseudepigrapha",
    "https://en.wikipedia.org/wiki/Healthcare_in_Taiwan",
    "https://en.wikipedia.org/wiki/List_of_New_Testament_verses_not_included_in_modern_English_translations",
    "https://en.wikipedia.org/wiki/Manny_Harris",
    "https://en.wikipedia.org/wiki/And_did_those_feet_in_ancient_time",
    "https://en.wikipedia.org/wiki/List_of_largest_houses_in_the_United_States",
    "https://en.wikipedia.org/wiki/Kit_Armstrong",
    "https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos",
    "https://en.wikipedia.org/wiki/Litmus_test_(politics)",
    "https://en.wikipedia.org/wiki/Depersonalization",
    "https://en.wikipedia.org/wiki/Statute_of_limitations",
    "https://en.wikipedia.org/wiki/Homoiousian",
    "https://en.wikipedia.org/wiki/Quine_(computing)",
    "https://en.wikipedia.org/wiki/Liar_paradox",
    "https://en.wikipedia.org/wiki/Nepalese_royal_massacre",
    "https://en.wikipedia.org/wiki/Peter_principle",
    "https://en.wikipedia.org/wiki/Molinism",
    "https://en.wikipedia.org/wiki/Booby_prize",
    "https://en.wikipedia.org/wiki/Principle_of_double_effect",
    "https://en.wikipedia.org/wiki/Tarrare",
    "https://en.wikipedia.org/wiki/Idiopathic_disease",
    "https://en.wikipedia.org/wiki/Language_of_Jesus",
    "https://en.wikipedia.org/wiki/Grey_goo",
    "https://en.wikipedia.org/wiki/Useful_idiot",
    "https://en.wikipedia.org/wiki/Taxi_medallion",
    "https://en.wikipedia.org/wiki/Arthur_Kornberg",
    "https://en.wikipedia.org/wiki/Tf%E2%80%93idf",
    "https://en.wikipedia.org/wiki/Giving_dap",
    "https://en.wikipedia.org/wiki/Euthyphro_dilemma",
    "https://en.wikipedia.org/wiki/Colgate%E2%80%93Cornell_football_rivalry",
    "https://en.wikipedia.org/wiki/Lazarus_sign",
    "https://en.wikipedia.org/wiki/Jonny_Kim",
    "https://en.wikipedia.org/wiki/NASA_Astronaut_Corps#Selection_groups",
    "https://en.wikipedia.org/wiki/Monowi,_Nebraska",
    "https://en.wikipedia.org/wiki/Takotsubo_cardiomyopathy",
    "https://en.wikipedia.org/wiki/Capgras_delusion",
    "https://en.wikipedia.org/wiki/Potemkin_village",
    "https://en.wikipedia.org/wiki/Sensory_processing_sensitivity",
    "https://en.wikipedia.org/wiki/Exonym_and_endonym",
    "https://en.wikipedia.org/wiki/Bilderberg_Meeting",
    "https://en.wikipedia.org/wiki/2.5D",
    "https://en.wikipedia.org/wiki/Right_to_be_forgotten",
    "https://en.wikipedia.org/wiki/Filioque",
    "https://en.wikipedia.org/wiki/Field_goal_range",
    "https://en.wikipedia.org/wiki/Prosopagnosia",
    "https://en.wikipedia.org/wiki/Levenshtein_distance",
    "https://en.wikipedia.org/wiki/Year_2038_problem",
    "https://en.wikipedia.org/wiki/Non-breaking_space",
    "https://en.wikipedia.org/wiki/Chekhov%27s_gun",
    "https://en.wikipedia.org/wiki/Quill_and_Dagger",
    "https://en.wikipedia.org/wiki/Novum_Testamentum_Graece",
    "https://en.wikipedia.org/wiki/Murphy%27s_Law_of_Love",
    "https://en.wikipedia.org/wiki/The_Perfect_Match_(TV_series)",
    "https://en.wikipedia.org/wiki/List_of_cognitive_biases",
    "https://en.wikipedia.org/wiki/Paul_Greengard",
    "https://en.wikipedia.org/wiki/Planned_obsolescence",
    "https://en.wikipedia.org/wiki/Graham's_number",
    "https://en.wikipedia.org/wiki/Centurion_Card",
    "https://en.wikipedia.org/wiki/Shibboleth",
    "https://en.wikipedia.org/wiki/Ken_McElroy",
    "https://en.wikipedia.org/wiki/Planet_Nine",
    "https://en.wikipedia.org/wiki/Flying_buttress",
    "https://en.wikipedia.org/wiki/Birthday_attack",
    "https://en.wikipedia.org/wiki/Fighting_in_ice_hockey",
    "https://en.wikipedia.org/wiki/Lie_group",
    "https://en.wikipedia.org/wiki/Cystinosis",
    "https://en.wikipedia.org/wiki/Subtle_Asian_Traits",
    "https://en.wikipedia.org/wiki/Pass_by_catastrophe",
    "https://en.wikipedia.org/wiki/Baader%E2%80%93Meinhof_effect",
    "https://en.wikipedia.org/wiki/Random_sample_consensus",
    "https://en.wikipedia.org/wiki/Flammagenitus_(cloud)",
    "https://en.wikipedia.org/wiki/Antimicrobial_properties_of_copper",
    "https://en.wikipedia.org/wiki/Kelly_criterion",
    "https://en.wikipedia.org/wiki/Ozymandias_(Breaking_Bad)",
    "https://en.wikipedia.org/wiki/Heat_index",
    "https://en.wikipedia.org/wiki/Zeitgeist",
    "https://en.wikipedia.org/wiki/Big_Three_(management_consultancies)",
    "https://en.wikipedia.org/wiki/Tonsillolith",
    "https://en.wikipedia.org/wiki/Epanalepsis",
    "https://en.wikipedia.org/wiki/Aleatoric_music",
    "https://en.wikipedia.org/wiki/Levant",
    "https://en.wikipedia.org/wiki/Teleology",
    "https://en.wikipedia.org/wiki/Ultra_high-net-worth_individual",
    "https://en.wikipedia.org/wiki/List_of_tallest_people",
    "https://en.wikipedia.org/wiki/List_of_medical_eponyms_with_Nazi_associations",
    "https://en.wikipedia.org/wiki/Muphry%27s_law",
    "https://en.wikipedia.org/wiki/Tyranny_of_small_decisions",
    "https://en.wikipedia.org/wiki/Alcohol_flush_reaction",
    "https://en.wikipedia.org/wiki/List_of_nuclear_close_calls",
    "https://en.wikipedia.org/wiki/Pareidolia",
    "https://en.wikipedia.org/wiki/Eradication_of_infectious_diseases",
    "https://en.wikipedia.org/wiki/Metonymy",
    "https://en.wikipedia.org/wiki/Jury_nullification",
    "https://en.wikipedia.org/wiki/List_of_medical_abbreviations:_A",
    "https://en.wikipedia.org/wiki/Maltese_cross",
    "https://en.wikipedia.org/wiki/Krzyzewskiville",
    "https://en.wikipedia.org/wiki/Cultured_pearl",
    "https://en.wikipedia.org/wiki/Veblen_good",
    "https://en.wikipedia.org/wiki/Pylon_(architecture)",
    "https://en.wikipedia.org/wiki/Mytheme",
    "https://en.wikipedia.org/wiki/Sator_Square",
    "https://en.wikipedia.org/wiki/Mise-en-sc%C3%A8ne",
    "https://en.wikipedia.org/wiki/Gedhun_Choekyi_Nyima",
    "https://en.wikipedia.org/wiki/Hygge",
    "https://en.wikipedia.org/wiki/Memento_mori",
    "https://en.wikipedia.org/wiki/Troxler's_fading",
    "https://en.wikipedia.org/wiki/Integration_Bee",
    "https://en.wikipedia.org/wiki/Chicago_Tylenol_murders",
    "https://en.wikipedia.org/wiki/4X",
    "https://en.wikipedia.org/wiki/Astroturfing",
    "https://en.wikipedia.org/wiki/DEFCON",
    "https://en.wikipedia.org/wiki/Gratis_versus_libre",
    "https://en.wikipedia.org/wiki/Sweater_curse",
    "https://en.wikipedia.org/wiki/Three_on_a_match",
    "https://en.wikipedia.org/wiki/Chapters_and_verses_of_the_Bible",
    "https://en.wikipedia.org/wiki/Biblical_clothing",
    "https://en.wikipedia.org/wiki/Arrears",
    "https://en.wikipedia.org/wiki/Apostrophe_(figure_of_speech)",
    "https://en.wikipedia.org/wiki/Etymological_fallacy",
    "https://en.wikipedia.org/wiki/Black_swan_theory",
    "https://en.wikipedia.org/wiki/List_of_unicorn_startup_companies",
    "https://en.wikipedia.org/wiki/Whataboutism",
    "https://en.wikipedia.org/wiki/Argumentum_a_fortiori",
    "https://en.wikipedia.org/wiki/Ordo_salutis",
    "https://en.wikipedia.org/wiki/Templeton_Prize",
    "https://en.wikipedia.org/wiki/Kalam_cosmological_argument",
    "https://en.wikipedia.org/wiki/Force_majeure",
    "https://en.wikipedia.org/wiki/Abilene_paradox",
    "https://en.wikipedia.org/wiki/Stendhal_syndrome",
    "https://en.wikipedia.org/wiki/Medicus_curat,_natura_sanat",
    "https://en.wikipedia.org/wiki/Mutual_intelligibility",
    "https://en.wikipedia.org/wiki/Thalassocracy",
    "https://en.wikipedia.org/wiki/Technological_singularity",
    "https://en.wikipedia.org/wiki/Human_capital_flight",
    "https://en.wikipedia.org/wiki/Liminality",
    "https://en.wikipedia.org/wiki/Tsundoku",
    "https://en.wikipedia.org/wiki/L%27esprit_de_l%27escalier",
    "https://en.wikipedia.org/wiki/Comparison_of_Danish,_Norwegian_Bokm%C3%A5l,_Norwegian_Nynorsk_and_Swedish",
    "https://en.wikipedia.org/wiki/Sabra_(person)",
    "https://en.wikipedia.org/wiki/False_friend",
    "https://en.wikipedia.org/wiki/Cymatics",
    "https://en.wikipedia.org/wiki/Heirloom_tomato",
    "https://en.wikipedia.org/wiki/Phrasal_verb",
    "https://en.wikipedia.org/wiki/NIMBY",
    "https://en.wikipedia.org/wiki/Minced_oath",
    "https://en.wikipedia.org/wiki/List_of_colleges_and_universities_in_the_United_States_by_endowment",
    "https://en.wikipedia.org/wiki/Jansenism",
    "https://en.wikipedia.org/wiki/Hypocorism",
    "https://en.wikipedia.org/wiki/Poet_Laureate_of_the_United_Kingdom",
    "https://en.wikipedia.org/wiki/Americana",
    "https://en.wikipedia.org/wiki/Taiwanese_people_in_New_York_City",
    "https://en.wikipedia.org/wiki/Autarky",
    "https://en.wikipedia.org/wiki/Curse_of_Tippecanoe",
    "https://en.wikipedia.org/wiki/Random_walk",
    "https://en.wikipedia.org/wiki/Apophenia",
    "https://en.wikipedia.org/wiki/Kibitzer",
    "https://en.wikipedia.org/wiki/Chess_piece_relative_value",
    "https://en.wikipedia.org/wiki/Risk_compensation",
    "https://en.wikipedia.org/wiki/Cobra_effect",
    "https://en.wikipedia.org/wiki/Desire_path",
    "https://en.wikipedia.org/wiki/Robert_S._Langer",
    "https://en.wikipedia.org/wiki/Solved_game",
    "https://en.wikipedia.org/wiki/Augury",
    "https://en.wikipedia.org/wiki/Cross_patt%C3%A9e",
    "https://en.wikipedia.org/wiki/Closed_city",
    "https://en.wikipedia.org/wiki/27_Club",
    "https://en.wikipedia.org/wiki/Sui_generis",
    "https://en.wikipedia.org/wiki/Ben_Franklin_effect",
    "https://en.wikipedia.org/wiki/Eye_dialect",
    "https://en.wikipedia.org/wiki/Reports_of_Streptococcus_mitis_on_the_Moon",
    "https://en.wikipedia.org/wiki/Tunguska_event",
    "https://en.wikipedia.org/wiki/Overton_window",
    "https://en.wikipedia.org/wiki/AlphaGo_versus_Lee_Sedol",
    "https://en.wikipedia.org/wiki/Thanatos",
    "https://en.wikipedia.org/wiki/God_of_the_gaps",
    "https://en.wikipedia.org/wiki/Alford_plea",
    "https://en.wikipedia.org/wiki/List_of_visionary_tall_buildings_and_structures",
    "https://en.wikipedia.org/wiki/Epiphenomenon",
    "https://en.wikipedia.org/wiki/Blackstone%27s_ratio",
    "https://en.wikipedia.org/wiki/Pluricentric_language",
    "https://en.wikipedia.org/wiki/Lindy_effect",
    "https://en.wikipedia.org/wiki/Teknonymy",
    "https://en.wikipedia.org/wiki/Variability_hypothesis",
    "https://en.wikipedia.org/wiki/Scientific_pitch",
    "https://en.wikipedia.org/wiki/Benford%27s_law",
    "https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life",
    "https://en.wikipedia.org/wiki/Voynich_manuscript",
    "https://en.wikipedia.org/wiki/Hebraization_of_surnames",
    "https://en.wikipedia.org/wiki/Predator_satiation",
    "https://en.wikipedia.org/wiki/Chi_Rho",
    "https://en.wikipedia.org/wiki/Cradle_of_civilization",
    "https://en.wikipedia.org/wiki/Attention_economy",
    "https://en.wikipedia.org/wiki/Strategy-stealing_argument",
    "https://en.wikipedia.org/wiki/Allelopathy",
    "https://en.wikipedia.org/wiki/Roman_naming_conventions",
    "https://en.wikipedia.org/wiki/Cognate",
    "https://en.wikipedia.org/wiki/Cadaver_Synod",
    "https://en.wikipedia.org/wiki/Linguistic_relativity",
    "https://en.wikipedia.org/wiki/Penney%27s_game",
    "https://en.wikipedia.org/wiki/Qualia",
    "https://en.wikipedia.org/wiki/Glory_to_Ukraine",
    "https://en.wikipedia.org/wiki/Barnum_effect",
    "https://en.wikipedia.org/wiki/Nomen_nescio",
    "https://en.wikipedia.org/wiki/Coastline_paradox",
    "https://en.wikipedia.org/wiki/Generation_name",
    "https://en.wikipedia.org/wiki/Nordic_cross_flag",
    "https://en.wikipedia.org/wiki/Cinematic_style_of_Christopher_Nolan",
    "https://en.wikipedia.org/wiki/List_of_calques",
    "https://en.wikipedia.org/wiki/List_of_diagnoses_characterized_as_pseudoscience",
    "https://en.wikipedia.org/wiki/1_%2B_2_%2B_3_%2B_4_%2B_%E2%8B%AF",
    "https://en.wikipedia.org/wiki/RAS_syndrome",
    "https://en.wikipedia.org/wiki/Pleonasm",
    "https://en.wikipedia.org/wiki/Hendiatris",
    "https://en.wikipedia.org/wiki/Brassica_oleracea",
    "https://en.wikipedia.org/wiki/Vantablack",
    "https://en.wikipedia.org/wiki/Protoplast_(religion)",
    "https://en.wikipedia.org/wiki/Flotsam,_jetsam,_lagan_and_derelict",
    "https://en.wikipedia.org/wiki/Vicarious_embarrassment",
    "https://en.wikipedia.org/wiki/Planned_community",
    "https://en.wikipedia.org/wiki/Irreversible_binomial",
    "https://en.wikipedia.org/wiki/Valonia_ventricosa",
    "https://en.wikipedia.org/wiki/Exploding_whale",
    "https://en.wikipedia.org/wiki/Uncanny_valley",
    "https://en.wikipedia.org/wiki/Verisimilitude",
    "https://en.wikipedia.org/wiki/McNamara_fallacy",
    "https://en.wikipedia.org/wiki/Activist_shareholder",
    "https://en.wikipedia.org/wiki/Ahkam",
    "https://en.wikipedia.org/wiki/Tommy_Lee_Jones",
    "https://en.wikipedia.org/wiki/Barber_surgeon",
    "https://en.wikipedia.org/wiki/Mudita",
    "https://en.wikipedia.org/wiki/Squircle",
    "https://en.wikipedia.org/wiki/Kleptoparasitism",
    "https://en.wikipedia.org/wiki/Mise_en_place",
    "https://en.wikipedia.org/wiki/Flanderization",
    "https://en.wikipedia.org/wiki/Photogrammetry",
    "https://en.wikipedia.org/wiki/Chicken_(game)",
    "https://en.wikipedia.org/wiki/Almost_surely",
    "https://en.wikipedia.org/wiki/Aphantasia",
    "https://en.wikipedia.org/wiki/Mourning_dove",
    "https://en.wikipedia.org/wiki/Via_media",
    "https://en.wikipedia.org/wiki/Reappropriation",
    "https://en.wikipedia.org/wiki/Formant",
    "https://en.wikipedia.org/wiki/Oyez",
    "https://en.wikipedia.org/wiki/Law_French",
    "https://en.wikipedia.org/wiki/Marine_snow",
    "https://en.wikipedia.org/wiki/Piercing_the_corporate_veil",
    "https://en.wikipedia.org/wiki/Lingua_franca",
    "https://en.wikipedia.org/wiki/Classical_language",
    "https://en.wikipedia.org/wiki/Salmon_P._Chase",
    "https://en.wikipedia.org/wiki/Big_Four_(banking)",
    "https://en.wikipedia.org/wiki/McCoy_Center",
    "https://en.wikipedia.org/wiki/Parsec",
    "https://en.wikipedia.org/wiki/Proxima_Centauri",
    "https://en.wikipedia.org/wiki/Toponymic_surname",
    "https://en.wikipedia.org/wiki/ABCC11",
    "https://en.wikipedia.org/wiki/Leap_second",
    "https://en.wikipedia.org/wiki/Head_bobble",
    "https://en.wikipedia.org/wiki/Kleptocracy",
    "https://en.wikipedia.org/wiki/Status_Quo_(Jerusalem_and_Bethlehem)",
    "https://en.wikipedia.org/wiki/Diegetic_music",
    "https://en.wikipedia.org/wiki/Legio_IX_Hispana",
    "https://en.wikipedia.org/wiki/Boston_Brahmin",
    "https://en.wikipedia.org/wiki/Brachydactyly_type_D",
    "https://en.wikipedia.org/wiki/Hairy_ball_theorem",
    "https://en.wikipedia.org/wiki/Christian_democracy",
    "https://en.wikipedia.org/wiki/G_factor_(psychometrics)",
    "https://en.wikipedia.org/wiki/Enjambment",
    "https://en.wikipedia.org/wiki/Muqarnas",
    "https://en.wikipedia.org/wiki/Verb%E2%80%93object%E2%80%93subject_word_order",
    "https://en.wikipedia.org/wiki/Annus_mirabilis",
    "https://en.wikipedia.org/wiki/Dancing_plague_of_1518",
    "https://en.wikipedia.org/wiki/Pontifex_maximus",
    "https://en.wikipedia.org/wiki/K%C3%A1rm%C3%A1n_line",
    "https://en.wikipedia.org/wiki/Miraculin",
    "https://en.wikipedia.org/wiki/Abjad",
    "https://en.wikipedia.org/wiki/Supertaster",
    "https://en.wikipedia.org/wiki/Revival_of_the_Hebrew_language",
    "https://en.wikipedia.org/wiki/Affirming_the_consequent",
    "https://en.wikipedia.org/wiki/Timeline_of_the_name_Palestine",
    "https://en.wikipedia.org/wiki/Diadochi",
    "https://en.wikipedia.org/wiki/Monarchies_of_Malaysia",
    "https://en.wikipedia.org/wiki/Theophoric_name",
    "https://en.wikipedia.org/wiki/Death_by_misadventure",
    "https://en.wikipedia.org/wiki/Antidicomarians",
    "https://en.wikipedia.org/wiki/List_of_Reformed_Baptists",
    "https://en.wikipedia.org/wiki/Congenital_insensitivity_to_pain",
    "https://en.wikipedia.org/wiki/North_Atlantic_garbage_patch",
    "https://en.wikipedia.org/wiki/Nine-dash_line",
    "https://en.wikipedia.org/wiki/Royal_we",
    "https://en.wikipedia.org/wiki/Cross_of_Saint_James",
    "https://en.wikipedia.org/wiki/Kavanah",
    "https://en.wikipedia.org/wiki/Heteronym_(linguistics)",
    "https://en.wikipedia.org/wiki/List_of_abbreviations_used_in_medical_prescriptions",
    "https://en.wikipedia.org/wiki/Animals_in_the_Bible",
    "https://en.wikipedia.org/wiki/Black%E2%80%93Scholes_model",
    "https://en.wikipedia.org/wiki/Heights_of_presidents_and_presidential_candidates_of_the_United_States",
    "https://en.wikipedia.org/wiki/Miasma_theory",
    "https://en.wikipedia.org/wiki/Illeism",
    "https://en.wikipedia.org/wiki/Hapax_legomenon",
    "https://en.wikipedia.org/wiki/Eton_College",
    "https://en.wikipedia.org/wiki/Phos_Hilaron",
    "https://en.wikipedia.org/wiki/Staple_food",
    "https://en.wikipedia.org/wiki/Dunbar%27s_number",
    "https://en.wikipedia.org/wiki/Humboldtian_model_of_higher_education",
    "https://en.wikipedia.org/wiki/TA-CD",
    "https://en.wikipedia.org/wiki/Arrow_(symbol)",
    "https://en.wikipedia.org/wiki/Year_zero",
    "https://en.wikipedia.org/wiki/Confusion_matrix",
    "https://en.wikipedia.org/wiki/Physiognomy",
    "https://en.wikipedia.org/wiki/Hamburger_button",
    "https://en.wikipedia.org/wiki/Code_smell",
    "https://en.wikipedia.org/wiki/Andr%C3%A9s_Escobar",
    "https://en.wikipedia.org/wiki/Locum",
    "https://en.wikipedia.org/wiki/Uncaught_third_strike",
    "https://en.wikipedia.org/wiki/Nobel_disease",
    "https://en.wikipedia.org/wiki/Per_stirpes",
    "https://en.wikipedia.org/wiki/Folly",
    "https://en.wikipedia.org/wiki/Recursive_islands_and_lakes",
    "https://en.wikipedia.org/wiki/Spite_house",
    "https://en.wikipedia.org/wiki/List_of_cities_claimed_to_be_built_on_seven_hills",
    "https://en.wikipedia.org/wiki/Tanganyika_laughter_epidemic",
    "https://en.wikipedia.org/wiki/Signed_zero",
    "https://en.wikipedia.org/wiki/Time_in_China",
    "https://en.wikipedia.org/wiki/Expletive_infixation",
    "https://en.wikipedia.org/wiki/List_of_English_words_containing_Q_not_followed_by_U",
    "https://en.wikipedia.org/wiki/Mamihlapinatapai",
    "https://en.wikipedia.org/wiki/Martian_language",
    "https://en.wikipedia.org/wiki/Isolating_language",
    "https://en.wikipedia.org/wiki/Diglossia",
    "https://en.wikipedia.org/wiki/Nominative_determinism",
    "https://en.wikipedia.org/wiki/9,10-Dithioanthracene",
    "https://en.wikipedia.org/wiki/26th_Congress_of_the_Communist_Party_of_the_Soviet_Union_(diamond)",
    "https://en.wikipedia.org/wiki/Smell_of_freshly_cut_grass",
    "https://en.wikipedia.org/wiki/Continental_drip",
    "https://en.wikipedia.org/wiki/Auto-brewery_syndrome",
    "https://en.wikipedia.org/wiki/DNA_origami",
    "https://en.wikipedia.org/wiki/Eigengrau",
    "https://en.wikipedia.org/wiki/Fiddler%27s_neck",
    "https://en.wikipedia.org/wiki/Jo_Cameron",
    "https://en.wikipedia.org/wiki/Mizab_al-Rahma",
    "https://en.wikipedia.org/wiki/Zipporah_at_the_inn",
    "https://en.wikipedia.org/wiki/Pope_John_numbering",
    "https://en.wikipedia.org/wiki/Omphalos_hypothesis",
    "https://en.wikipedia.org/wiki/Non-canonical_books_referenced_in_the_Bible",
    "https://en.wikipedia.org/wiki/Ring_of_the_Fisherman",
    "https://en.wikipedia.org/wiki/Papal_conclave",
    "https://en.wikipedia.org/wiki/Primus_inter_pares",
    "https://en.wikipedia.org/wiki/Lina_Khan",
    "https://en.wikipedia.org/wiki/Nobel_Prize_controversies",
    "https://en.wikipedia.org/wiki/Meleke",
    "https://en.wikipedia.org/wiki/National_poet",
    "https://en.wikipedia.org/wiki/Tintern_Abbey",
    "https://en.wikipedia.org/wiki/Dissolution_of_the_monasteries",
    "https://en.wikipedia.org/wiki/Carcinisation",
    "https://en.wikipedia.org/wiki/White_Shark_Caf%C3%A9",
    "https://en.wikipedia.org/wiki/Jus_soli",
    "https://en.wikipedia.org/wiki/Monopsony",
    "https://en.wikipedia.org/wiki/Strauss%E2%80%93Howe_generational_theory",
    "https://en.wikipedia.org/wiki/Saeculum",
    "https://en.wikipedia.org/wiki/List_of_antibiotics",
    "https://en.wikipedia.org/wiki/Stark_Law",
    "https://en.wikipedia.org/wiki/Jevons_paradox",
    "https://en.wikipedia.org/wiki/Logical_order_of_God%27s_decrees",
    "https://en.wikipedia.org/wiki/History_of_ancient_Israel_and_Judah",
    "https://en.wikipedia.org/wiki/Koine_Greek",
    "https://en.wikipedia.org/wiki/Biblical_Hebrew",
    "https://en.wikipedia.org/wiki/Biblical_Aramaic",
    "https://en.wikipedia.org/wiki/Patristics",
    "https://en.wikipedia.org/wiki/Wikipedia_coverage_of_death",
    "https://en.wikipedia.org/wiki/What_Is_It_Like_to_Be_a_Bat%3F",
    "https://en.wikipedia.org/wiki/Lenticular_cloud",
    "https://en.wikipedia.org/wiki/Wengen",
    "https://en.wikipedia.org/wiki/Ma_Nishtana",
    "https://en.wikipedia.org/wiki/Information_asymmetry",
    "https://en.wikipedia.org/wiki/As-salamu_alaykum",
    "https://en.wikipedia.org/wiki/Low-background_steel",
    "https://en.wikipedia.org/wiki/Strategic_lawsuit_against_public_participation",
    "https://en.wikipedia.org/wiki/Kaddish",
    "https://en.wikipedia.org/wiki/Twelvefold_way",
    "https://en.wikipedia.org/wiki/Polymath",
    "https://en.wikipedia.org/wiki/Heritability_of_IQ",
    "https://en.wikipedia.org/wiki/Saint_Thomas_Christians",
    "https://en.wikipedia.org/wiki/Chinese_folk_religion",
    "https://en.wikipedia.org/wiki/Ark_of_the_Covenant",
    "https://en.wikipedia.org/wiki/1936_Summer_Olympics",
    "https://en.wikipedia.org/wiki/Fu-Go_balloon_bomb",
    "https://en.wikipedia.org/wiki/Kong%C5%8D_Gumi",
    "https://en.wikipedia.org/wiki/List_of_oldest_companies",
    "https://en.wikipedia.org/wiki/ADX_Florence",
    "https://en.wikipedia.org/wiki/Athletics_at_the_1904_Summer_Olympics_%E2%80%93_Men%27s_marathon",
    "https://en.wikipedia.org/wiki/As_Slow_as_Possible",
    "https://en.wikipedia.org/wiki/Assassination_of_Kim_Jong-nam",
    "https://en.wikipedia.org/wiki/Ararat_anomaly",
    "https://en.wikipedia.org/wiki/Fibrodysplasia_ossificans_progressiva",
    "https://en.wikipedia.org/wiki/Long-term_nuclear_waste_warning_messages",
    "https://en.wikipedia.org/wiki/Lost_Cosmonauts",
    "https://en.wikipedia.org/wiki/Loveland_frog",
    "https://en.wikipedia.org/wiki/Rain_of_animals",
    "https://en.wikipedia.org/wiki/Roanoke_Colony",
    "https://en.wikipedia.org/wiki/Wow!_signal",
    "https://en.wikipedia.org/wiki/North_Korean_ghost_ships",
    "https://en.wikipedia.org/wiki/Norse_colonization_of_North_America",
    "https://en.wikipedia.org/wiki/Language_secessionism",
    "https://en.wikipedia.org/wiki/Akkadian_language",
    "https://en.wikipedia.org/wiki/Martha%27s_Vineyard_Sign_Language",
    "https://en.wikipedia.org/wiki/Sky_burial",
    "https://en.wikipedia.org/wiki/Panchen_Lama",
    "https://en.wikipedia.org/wiki/Simen_Agdestein",
    "https://en.wikipedia.org/wiki/Merchant_Marine_Act_of_1920",
];

const getRandomArticles = (bookmarks, count) => {
    const shuffled = bookmarks.sort(() => 0.5 - Math.random());
    return shuffled.slice(0, count);
};

const fetchArticlePreview = async (url) => {
    const title = url.split("/").pop();
    const apiUrl = `https://en.wikipedia.org/api/rest_v1/page/summary/${title}`;
    try {
        const response = await fetch(apiUrl);
        if (!response.ok) throw new Error("Failed to fetch article preview");
        return await response.json();
    } catch (error) {
        console.error("Error fetching preview:", error);
        return null;
    }
};

const displayArticles = async (count = 10) => {
    const articleContainer = document.getElementById("articleContainer");
    articleContainer.innerHTML = ""; // Clear existing articles
    const randomArticles = getRandomArticles(bookmarks, count);

    for (const url of randomArticles) {
        const preview = await fetchArticlePreview(url);
        if (preview) {
            const articleCard = document.createElement("div");
            articleCard.classList.add("article-card");

            articleCard.innerHTML = `
                <img src="${preview.thumbnail?.source || './assets/images/wikipedia-logo.png'}" alt="${preview.title}">
                <h3>${preview.title}</h3>
                <p>${preview.extract}</p>
                <a href="${preview.content_urls.desktop.page}" target="_blank">Read more</a>
            `;

            articleContainer.appendChild(articleCard);
        }
    }
};

const populateBookmarks = () => {
    const bookmarkList = document.getElementById("bookmarkList");
    const sortedBookmarks = bookmarks.sort((a, b) => a.localeCompare(b));

    sortedBookmarks.forEach((url) => {
        const title = url.split("/").pop().replace(/_/g, " ");
        const listItem = document.createElement("li");
        listItem.innerHTML = `<a href="${url}" target="_blank">${title}</a>`;
        bookmarkList.appendChild(listItem);
    });
};

const toggleBanner = () => {
    const banner = document.getElementById("bookmarkBanner");
    const toggleButton = document.getElementById("toggleBanner");
    if (banner.style.display === "none" || banner.style.display === "") {
        banner.style.display = "block";
        toggleButton.textContent = "Hide All Bookmarks";
    } else {
        banner.style.display = "none";
        toggleButton.textContent = "Show All Bookmarks";
    }
};

document.getElementById("toggleBanner").addEventListener("click", toggleBanner);

document.getElementById("refreshButton").addEventListener("click", () => {
    const count = parseInt(document.getElementById("articleCount").value, 10) || 10;
    displayArticles(count);
});

displayArticles();
populateBookmarks();